<a href="https://colab.research.google.com/github/Iyaiyak/DavinNayakaPandya_2602163336_SC/blob/main/Sesi%201/Session_1_Lab_Scientific_Computing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import time
print(time.ctime())

Wed Mar 15 03:52:55 2023


In [2]:
import numpy as np

In [3]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [5]:
y = np.array([[1, 4, 3], [5, 3, 7]])
y

array([[1, 4, 3],
       [5, 3, 7]])

In [6]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[2,3,4], [1,2,3], [6,7,8]]])
z

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[2, 3, 4],
        [1, 2, 3],
        [6, 7, 8]]])

In [14]:
x = 3
if 1<x<2:
  y = 2
if 2<x<4:
  y = 4
else:
  y = 0
print(y)

4


In [7]:
def my_adder(a, b, c):
  """
  function to sum the 3 numbers
  Input: 3 numbers a, b, c
  Output: the sum of a, b, and c
  author:
  date:
  """
  # this is the summation
  out = a + b + c

  return out

In [8]:
my_adder(1,2,3)

6

In [9]:
help(my_adder)

Help on function my_adder in module __main__:

my_adder(a, b, c)
    function to sum the 3 numbers
    Input: 3 numbers a, b, c
    Output: the sum of a, b, and c
    author:
    date:



In [10]:
def my_thermo_stat(temp, desired_temp):
  if temp < desired_temp - 5:
    status = "Heat"
  elif temp > desired_temp + 5:
    status = "AC"
  else:
    status = "off"
  return status

In [11]:
status = my_thermo_stat(65,75)
print(status)

Heat


In [12]:
status = my_thermo_stat(75,65)
print(status)

AC


In [13]:
status = my_thermo_stat(65,63)
print(status)

off
